name: Simple Docker Pipeline

on: [push]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Docker
        run: sudo apt-get install -y docker.io docker-compose
      
      - name: Run smoke test
        run: |
          cd server
          ./tests/smoke_test.sh

  deploy-local:
    needs: smoke-test
    runs-on: self-hosted  # Локальный раннер
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy
        run: |
          cd server
          docker-compose down || true
          docker-compose up -d --build